@@include('libs/smoothScroll.js', {})
@@include('libs/tippy.js', {})
@@include('libs/swiper.min.js', {})
@@include('libs/nouislider.js', {})
@@include('libs/simplebar.js', {})
@@include('libs/inputmask.min.js', {})
@@include('libs/wNumb.min.js', {})
